name: ${name}
version: ${version}
main: ${group}.${name}
api-version: '1.21'
author: FlyAwayMaking
website: https://github.com/flyawaymaking
description: Убирает ограничения наковальни

commands:
  anvilboundless:
    description: Основная команда плагина
    usage: /<command> [reload]
    permission: anvilboundless.reload

permissions:
  anvilboundless.reload:
    description: Позволяет перезагружать конфиг
    default: op
